spring:
  config:
    import: optional:classpath:configuration.properties

  application:
    name: authentication-service

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database: ${DB}
    database-platform: ${DB_PLT}

  webflux:
    base-path: /

server:
    port: ${PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

    instance:
      hostname: localhost

application:
  security:
    jwt:
      secret-key: ${KEY}
      expiration: ${EXPIRATION}
  gateway:
    url: ${GATEWAY_URL}

logging:
  level:
    com.nutria.app: ${LOG_LEVEL}
    org.springframework.web.reactive.function.client: ${WEBCLIENT_LOG_LEVEL}


