spring:
  config:
    import: optional:classpath:configuration.properties

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthFilter

        - id: image-processing-service
          uri: lb://image-processing-service
          predicates:
            - Path=/api/v1/food-trace/**
          filters:
            - name: AuthFilter

server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
application:
  security:
    jwt:
      secret-key: ${KEY}
