spring:
  config:
    import: optional:classpath:configuration.properties

  application:
    name: api-gateway

  cloud:

    gateway:

      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: AuthFilter
            - name: CircuitBreaker
              args:
                name: circuitBreaker
                fallbackUri: forward:/fallbackCall

        - id: image-processing-service
          uri: lb://image-processing-service
          predicates:
            - Path=/api/v1/food-trace/**
          filters:
            - name: AuthFilter

        - id: trace-nutrition-service
          uri: lb://trace-nutrition-service
          predicates:
            - Path=/api/v1/nutrition-trace/**
          filters:
            - name: AuthFilter
            - name: CircuitBreaker
              args:
                name: circuitBreaker
                fallbackUri: forward:/fallbackCall
  main:
    web-application-type: reactive


server:
  port: ${PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
    registry-fetch-interval-seconds: 5
    cache-refresh-executor-thread-pool-size: 2


application:
  security:
    jwt:
      secret-key: ${KEY}

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50  # The threshold at which the circuit breaker will open (50% failure)
        slidingWindowSize: 10     # Number of requests to consider for failure rate calculation
        permittedNumberOfCallsInHalfOpenState: 5  # Number of requests allowed in half-open state
        waitDurationInOpenState: 5000ms

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG